plugins {
    id "kotlin"
}

import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
import org.jetbrains.kotlin.gradle.tasks.UsesKotlinJavaToolchain
import org.gradle.internal.os.OperatingSystem

String jdk11Folder
if (OperatingSystem.current().isWindows()) {
    jdk11Folder = "win"
} else if (OperatingSystem.current().isLinux()) {
    jdk11Folder = "linux"
} else if (OperatingSystem.current().isMacOsX()) {
    if ("aarch64" == System.getProperty("os.arch")) {
        jdk11Folder = "mac-arm64/Contents/Home"
    } else {
        jdk11Folder = "mac/Contents/Home"
    }
} else {
    throw new IllegalStateException("Unsupported operating system: " + OperatingSystem.current())
}

tasks.withType(KotlinCompile).configureEach {
    kotlinOptions {
        jvmTarget = "11"
        apiVersion = "2.0"
        languageVersion = "2.0"
        freeCompilerArgs = ((freeCompilerArgs + ["-Xjvm-default=all-compatibility", "-Xlambdas=class", "-Xsam-conversions=class"]) as Set) as List
    }
}

String jdk11Home = "${rootDir.parent}/prebuilts/studio/jdk/jdk11/$jdk11Folder"
project.tasks
        .withType(UsesKotlinJavaToolchain.class)
        .configureEach {
            it.kotlinJavaToolchain.jdk.use(
                    jdk11Home,
                    JavaVersion.VERSION_11
            )
        }

// Workaround for https://youtrack.jetbrains.com/issue/KT-54207
tasks.named("kotlinSourcesJar").configure {
    it.enabled = false
}