plugins {
    id "kotlin"
}

import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
import org.jetbrains.kotlin.gradle.tasks.UsesKotlinJavaToolchain
import org.gradle.internal.os.OperatingSystem

String jdk17Folder
if (OperatingSystem.current().isWindows()) {
    jdk17Folder = "win"
} else if (OperatingSystem.current().isLinux()) {
    jdk17Folder = "linux"
} else if (OperatingSystem.current().isMacOsX()) {
    if ("aarch64" == System.getProperty("os.arch")) {
        jdk17Folder = "mac-arm64/Contents/Home"
    } else {
        jdk17Folder = "mac/Contents/Home"
    }
} else {
    throw new IllegalStateException("Unsupported operating system: " + OperatingSystem.current())
}

tasks.withType(KotlinCompile).configureEach {
    kotlinOptions {
        jvmTarget = "17"
        apiVersion = "2.0"
        languageVersion = "2.0"
        freeCompilerArgs = ((freeCompilerArgs + ["-Xjvm-default=all-compatibility", "-Xsam-conversions=class"]) as Set) as List
    }
}

String jdk17Home = "${rootDir.parent}/prebuilts/studio/jdk/jdk17/$jdk17Folder"
project.tasks
        .withType(UsesKotlinJavaToolchain.class)
        .configureEach {
            it.kotlinJavaToolchain.jdk.use(
                    jdk17Home,
                    JavaVersion.VERSION_17
            )
        }

// Workaround for https://youtrack.jetbrains.com/issue/KT-54207
tasks.named("kotlinSourcesJar").configure {
    it.enabled = false
}