filegroup(
    name = "agp_gradle_build_files",
    srcs = glob([
        "**/*.gradle",
        "**/*.gradle.kts",
        "src/main/groovy/com/android/tools/internal/*.java",
        "src/main/groovy/com/android/tools/internal/license/*.java",
        "src/main/java/com/android/tools/internal/*.java",
        "src/main/java/com/android/tools/internal/artifacts/*.java",
        "src/main/java/com/android/tools/internal/artifacts/offline/*.java",
        "src/main/java/com/android/tools/internal/bazel/*.java",
        "src/main/java/com/android/tools/internal/dackka/*.java",
        "src/main/java/com/android/tools/internal/metalava/*.java",
        "src/main/java/com/android/tools/internal/testing/*.java",
        "src/test/java/com/android/tools/internal/artifacts/*.java",
        "src/test/java/com/android/tools/internal/testing/*.java",
        "src/**/*.groovy",
        "src/**/*.kt",
        "src/*/resources/**",
    ]),
    visibility = [
        "//tools/base/build-system:__pkg__",
        "//tools/base/firebase/testlab/testlab-gradle-plugin:__pkg__",
        "//tools/base/journeys:__subpackages__",
        "//tools/base/preview/screenshot/screenshot-test-gradle-plugin:__pkg__",
        "//tools/base/utp:__pkg__",
    ],
)
