apply plugin: 'groovy-gradle-plugin'
apply plugin: 'idea'
apply plugin: 'maven-publish'

repositories {
    maven { url = "$rootDir/../../prebuilts/tools/common/m2/repository" }
    maven { url = "$rootDir/../../prebuilts/tools/common/m2/internal" }
}

buildDir = "../../out/build/buildSrc/build"

apply from: 'base/version.gradle'

dependencies {
    implementation gradleApi()
    implementation localGroovy()

    implementation "com.googlecode.jarjar:jarjar:1.3"
    implementation libs.apache_commons_io
    implementation libs.guava
    implementation ('com.google.protobuf:protobuf-gradle-plugin:0.8.10') {
        exclude group: 'org.apache.maven', module: 'maven-plugin-api'
    }
    implementation libs.apache_commons_lang
    implementation "org.pegdown:pegdown:1.1.0"
    implementation libs.jsoup
    implementation libs.kotlin_gradle_plugin

    testImplementation libs.junit
}

validatePlugins {
    getFailOnWarning().set(false)
}

// See README.
sourceSets {
    main {
        groovy {
            srcDir 'src/fromGradle/groovy'
        }

        resources {
            srcDir 'src/fromGradle/resources'
        }
    }
}

// Make sure that we are compiling with a valid JDK. This can be overridden by setting the
// 'JAVA_FOR_TESTS' environment variable (to, e.g., '1.6')
task('checkJavaVersion').doLast {

    def requiredJdkVersion = JavaVersion.VERSION_11
    def javaForTests = System.getenv('JAVA_FOR_TESTS')
    if (javaForTests != null) {
        requiredJdkVersion = JavaVersion.toVersion(javaForTests)
    }

    def jvmVersion = JavaVersion.current()
    if (jvmVersion != requiredJdkVersion) {
        throw new RuntimeException("Tools need to be compiled with Java $requiredJdkVersion, you are using Java $jvmVersion.")
    }
}

assemble.dependsOn checkJavaVersion
