#!/usr/bin/env python
#
# Copyright 2021 - The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the',  help='License');
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an',  help='AS IS' BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import hashlib
import logging
import os
import platform
from functools import partial

from utils import AOSP_ROOT, PYTHON_EXE, platform_to_cmake_target, run
import subprocess
import sys


class QemuBuilder(object):
    """A qemu builder builds standard qemu, and extracts the cmake include file from the build."""

    _QEMU_DIR = os.path.join(AOSP_ROOT, "external", "qemu")

    _QEMU_BUILD_SCRIPT = os.path.join(
        _QEMU_DIR,
        "android",
        "scripts",
        "unix",
        "build-qemu-android.sh",
    )

    _CMAKE_GEN_SCRIPT = os.path.join(
        _QEMU_DIR,
        "android-qemu2-glue",
        "scripts",
        "gen-cmake.py",
    )

    def __init__(self, target, dist_dir, out_dir, cfg):
        self.target = target
        self.host = platform_to_cmake_target(target)
        self.out = os.path.join(out_dir, "qemu_build")
        self.dist = dist_dir
        self.env = cfg.get_env()

    def build(self):
        run(
            [
                QemuBuilder._QEMU_BUILD_SCRIPT,
                "--build-dir={}".format(self.out),
                "--host={}".format(self.host),
                "--verbose",
            ],
            self.env,
            "qemu",
        )

    def gen_cmake(self):
        run(
            [
                PYTHON_EXE,
                QemuBuilder._CMAKE_GEN_SCRIPT,
                "-r",
                os.path.join(AOSP_ROOT, "external", "qemu"),
                "-i",
                self.out,
                "-o",
                self.dist,
                "-s",
                self.host,
                "-v",
            ],
            self.env,
            "qemu",
        )

    def can_validate(self):
        machine = platform.system().lower()
        if platform.machine() == "arm64":
            machine += "_aarch64"

        crosscompile = self.target != machine

        if crosscompile:
            # Darwin TBD
            return self.target in ["linux_aarch64", "windows"]

        # We need posix to build qemu
        return self.target != "windows"

    def _sha256(self, fname):
        sha = hashlib.sha256()
        with open(fname, "rb") as f:
            for chunk in iter(partial(f.read, 1024 * 64), b""):
                sha.update(chunk)
        return sha.hexdigest()

    def compare_cmake(self):
        cmake_inc = "cmake-main.{}.inc".format(self.host)
        src = os.path.join(QemuBuilder._QEMU_DIR, cmake_inc)
        # Expected is the autogenerated cmake include from the
        # current qemu build.
        expected = os.path.join(self.dist, cmake_inc)

        try:
            cmd = subprocess.check_output(["diff", "-w", src, expected])
        except subprocess.CalledProcessError as err:
            logging.error(
                "Please apply the changes below, or copy the updated {}, from artifacts:".format(
                    cmake_inc
                )
            )
            logging.error(
                "-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
            )
            sys.stderr.write(
                "patch  --ignore-whitespace {} << 'EOF'\n".format(cmake_inc)
            )
            sys.stderr.write(err.output.decode("utf-8"))
            sys.stderr.write("EOF\n")
            raise Exception("Mismatch of expected: {} != {}!".format(expected, src))

    def validate(self):
        if not self.can_validate():
            logging.info("Cannot validate qemu build.. skipping")
            return

        logging.info("Validating qemu..")
        self.build()
        self.gen_cmake()
        self.compare_cmake()
