/*
 * Copyright (C) 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.android.tools.internal.metalava;

import com.android.tools.internal.AgpVersion;
import com.android.tools.internal.TaskUtils;
import com.google.common.collect.Lists;
import org.gradle.api.DefaultTask;
import org.gradle.api.file.ConfigurableFileCollection;
import org.gradle.api.file.DirectoryProperty;
import org.gradle.api.provider.Property;
import org.gradle.api.tasks.Classpath;
import org.gradle.api.tasks.CompileClasspath;
import org.gradle.api.tasks.Input;
import org.gradle.api.tasks.InputDirectory;
import org.gradle.api.tasks.InputFiles;
import org.gradle.api.tasks.PathSensitive;
import org.gradle.api.tasks.PathSensitivity;
import org.gradle.api.tasks.TaskAction;
import org.gradle.api.tasks.options.Option;
import org.gradle.workers.WorkerExecutor;
import javax.inject.Inject;
import java.io.File;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

/**
 Task that given current and reference api signature files (generated by metalava) finds if there are any
 binary compatibility breaking changes between them.

 To run manually:
 ./gradlew :base:gradle-api:checkApiCompatibility --current-version="<VERSION>" --reference-version="<VERSION>"
 **/
public abstract class CheckApiCompatibilityTask extends DefaultTask {
    @CompileClasspath
    public abstract ConfigurableFileCollection getClasspath();

    @Classpath
    public abstract ConfigurableFileCollection getMetalavaClasspath();

    @Inject
    public abstract WorkerExecutor getWorkerExecutor();

    @Input
    public abstract Property<String> getAgpBuildVersion();

    @InputDirectory
    public abstract DirectoryProperty getInputDirectory();

    @InputFiles
    @PathSensitive(PathSensitivity.RELATIVE)
    public abstract DirectoryProperty getPreviousApisDirectory();

    @Input
    @org.gradle.api.tasks.Optional
    @Option(option = "current-version", description = "The current AGP version")
    public abstract Property<String> getCurrentVersion();

    @Input
    @org.gradle.api.tasks.Optional
    @Option(option = "reference-version", description = "The reference AGP version to check compatibility against")
    public abstract Property<String> getReferenceVersion();

    @TaskAction
    public void exec() {
        File currentApiSignatureFile;
        File referenceApiSignatureFile;

        if (getReferenceVersion().isPresent()) {
            referenceApiSignatureFile = getPreviousApisDirectory().get().file(getReferenceVersion().get() + ".txt").getAsFile();
            if (!referenceApiSignatureFile.exists()) {
                throw new RuntimeException(
                        "Supplied previous-version (" + getReferenceVersion().get() + ") is not present in previous-gradle-apis folder."
                );
            }
        } else {
            Optional<AgpVersion> previousStableVersion = getPreviousApisDirectory().getAsFileTree().getFiles().stream()
                    .map(file -> AgpVersion.parseFileNameOrNull(file.getName()))
                    .filter(Objects::nonNull).max(Comparator.naturalOrder());
            if (previousStableVersion.isEmpty()) {
                throw new RuntimeException("I tried to find the latest API signature file in previous-gradle-apis folder" +
                        "but could not find one. Please run ./gradlew generateOldApis to generate them and then generate release notes");
            }
            referenceApiSignatureFile = getPreviousApisDirectory().get().file(previousStableVersion.get() + ".txt").getAsFile();
        }

        if (getCurrentVersion().isPresent()) {
            currentApiSignatureFile = getPreviousApisDirectory().get().file(getCurrentVersion().get() + ".txt").getAsFile();

            if (!currentApiSignatureFile.exists()) {
                throw new RuntimeException(
                        "Supplied current-version (" + getCurrentVersion().get() + ") is not present in previous-gradle-apis folder."
                );
            }
        } else {
            currentApiSignatureFile = getInputDirectory().get().file("current.txt").getAsFile();
        }

        AgpVersion currentVersion = AgpVersion.parseFileNameOrNull(currentApiSignatureFile.getName());
        // if currentApiSignatureFile points to current.txt
        if (currentVersion == null) {
            currentVersion = AgpVersion.parseOrNull(getAgpBuildVersion().get());
        }
        AgpVersion referenceVersion = AgpVersion.parseFileNameOrNull(referenceApiSignatureFile.getName());

        if (currentVersion == null) {
            throw new RuntimeException ("Supplied current file does not exist !!");
        }
        if (referenceVersion == null) {
            throw new RuntimeException ("Supplied reference file does not exist !!");
        }

        Boolean allowBreakingChanges = shouldAllowBreakingChanges(currentVersion, referenceVersion);
        List<String> args = getCompatibilityArguments(
                currentApiSignatureFile.getPath(),
                referenceApiSignatureFile.getPath(),
                allowBreakingChanges
        );

        getWorkerExecutor().noIsolation().submit(
                MetalavaWorkAction.class,
                params -> {
                    params.getArgs().set(args);
                    params.getMetalavaClasspath().set(getMetalavaClasspath());
                    params.getK2UastEnabled().set(true);
                }
        );
    }

    private Boolean shouldAllowBreakingChanges(AgpVersion currentVersion, AgpVersion referenceVersion) {
        return currentVersion.getMajor() != referenceVersion.getMajor();
    }

    private List<String> getCompatibilityArguments(
            String currentVersionFilePath,
            String referenceVersionFilePath,
            boolean allowBreakingChanges
    ) {
        ArrayList<String> args = Lists.newArrayList(
                "--classpath",
                TaskUtils.asArg(getClasspath()),
                "--source-files",
                currentVersionFilePath,
                "--check-compatibility:api:released",
                referenceVersionFilePath,
                "--warnings-as-errors",
                "--error-message:compatibility:released",
                CompatibilityCheckError
        );

        if (allowBreakingChanges) {
            args.add("--hide-category");
            args.add("Compatibility");
        }

        return args;
    }

    String CompatibilityCheckError = "Your change has API compatibility issues between minor versions of AGP.";
}
