/*
 * Copyright (C) 2019 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.android.tools.internal;

import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import javax.inject.Inject;
import org.gradle.api.DefaultTask;
import org.gradle.api.file.DirectoryProperty;
import org.gradle.api.model.ObjectFactory;
import org.gradle.api.plugins.ExtraPropertiesExtension;
import org.gradle.api.provider.Property;
import org.gradle.api.tasks.Input;
import org.gradle.api.tasks.OutputDirectory;
import org.gradle.api.tasks.TaskAction;

public class VersionPropertiesWriter extends DefaultTask {

    private final Property<String> baseVersion, buildVersion, apiVersion, nativeApiVersion;
    private final Property<String> outputFilePath;
    private final DirectoryProperty outputDirectory;

    @Inject
    public VersionPropertiesWriter(ObjectFactory objectFactory) {
        baseVersion = objectFactory.property(String.class);
        buildVersion = objectFactory.property(String.class);
        apiVersion = objectFactory.property(String.class);
        nativeApiVersion = objectFactory.property(String.class);
        outputFilePath = objectFactory.property(String.class);
        outputDirectory = objectFactory.directoryProperty();
        readValueFromExt(baseVersion, "baseVersion");
        readValueFromExt(buildVersion, "buildVersion");
        readValueFromExt(apiVersion, "apiVersion");
        readValueFromExt(nativeApiVersion, "nativeApiVersion");
    }

    private void readValueFromExt(Property<String> property, String extName) {
        property.set(
                getProject()
                        .getProviders()
                        .provider(
                                () -> {
                                    ExtraPropertiesExtension extraProperties =
                                            getProject()
                                                    .getRootProject()
                                                    .getExtensions()
                                                    .getExtraProperties();
                                    if (extraProperties.has(extName)) {
                                        Object value = extraProperties.get(extName);
                                        if (value != null) {
                                            return value.toString();
                                        }
                                    }
                                    return null;
                                }));
    }

    @Input
    public Property<String> getBaseVersion() {
        return baseVersion;
    }

    @Input
    public Property<String> getBuildVersion() {
        return buildVersion;
    }

    @Input
    public Property<String> getApiVersion() {
        return apiVersion;
    }

    @Input
    public Property<String> getNativeApiVersion() {
        return nativeApiVersion;
    }

    @Input
    public Property<String> getOutputFilePath() {
        return outputFilePath;
    }

    @OutputDirectory
    public DirectoryProperty getOutputDirectory() {
        return outputDirectory;
    }

    @TaskAction
    public void writeFile() throws IOException {
        Path path = outputDirectory.file(outputFilePath).get().getAsFile().toPath();
        Files.createDirectories(path.getParent());
        try (BufferedWriter writer = Files.newBufferedWriter(path)) {
            writer.write("# Generated by VersionPropertiesWriter\n");
            writer.write("baseVersion=");
            writer.write(baseVersion.get());
            writer.write("\n");
            writer.write("buildVersion=");
            writer.write(buildVersion.get());
            writer.write("\n");
            writer.write("apiVersion=");
            writer.write(apiVersion.get());
            writer.write("\n");
            writer.write("nativeApiVersion=");
            writer.write(nativeApiVersion.get());
            writer.write("\n");
        }
    }
}
