/*
 * Copyright (C) 2019 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.android.tools.internal;

import java.io.BufferedWriter;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Properties;
import java.util.jar.JarEntry;
import java.util.jar.JarFile;

import org.gradle.api.DefaultTask;
import org.gradle.api.file.ConfigurableFileCollection;
import org.gradle.api.file.DirectoryProperty;
import org.gradle.api.provider.Property;
import org.gradle.api.tasks.Classpath;
import org.gradle.api.tasks.Input;
import org.gradle.api.tasks.OutputDirectory;
import org.gradle.api.tasks.TaskAction;

public abstract class VersionPropertiesWriter extends DefaultTask {

    @Classpath
    public abstract ConfigurableFileCollection getVersionPropertiesSourceInput();
    @Input
    public abstract Property<String> getOutputFilePath();

    @OutputDirectory
    public abstract DirectoryProperty getOutputDirectory();

    @TaskAction
    public void writeFile() throws IOException {
        Properties properties = new Properties();
        for (File root : getVersionPropertiesSourceInput()) {
            try(JarFile jar = new JarFile(root)) {
                JarEntry entry = jar.getJarEntry("com/android/version.properties");
                if (entry != null) {
                    properties.load(jar.getInputStream(entry));
                    break;
                }
            }
        }

        Path path = getOutputDirectory().file(getOutputFilePath()).get().getAsFile().toPath();
        Files.createDirectories(path.getParent());
        try (BufferedWriter writer = Files.newBufferedWriter(path)) {
            writer.write("# Generated by VersionPropertiesWriter\n");
            writer.write("baseVersion=");
            writer.write(properties.getProperty("baseVersion"));
            writer.write("\n");
            writer.write("buildVersion=");
            writer.write(properties.getProperty("buildVersion"));
            writer.write("\n");
            writer.write("apiVersion=");
            writer.write(properties.getProperty("apiVersion"));
            writer.write("\n");
            writer.write("nativeApiVersion=");
            writer.write(properties.getProperty("nativeApiVersion"));
            writer.write("\n");
        }
    }
}
