<project name="Consolidate Gradle Coverage Reports" xmlns:jacoco="antlib:org.jacoco.ant">
  <taskdef uri="antlib:org.jacoco.ant" resource="org/jacoco/ant/antlib.xml">
    <classpath path="./idea/plugins/coverage/lib/jacocoant.jar"/>
  </taskdef>
  <target name="report">
    <jacoco:report>
      <executiondata>
        <fileset dir="../out/" includes="**/*.exec"/>
      </executiondata>
      <structure name="Android Studio (Gradle)">
        <classfiles>
          <fileset
            dir="../out/"
            includes="**/*.class"
            excludes="**/GRADLE_USER_HOME/*/caches/** .gradle/** **/example/** **/test*/**"
          />
        </classfiles>
        <sourcefiles encoding="UTF-8">
          <fileset dir="./adt/idea/adt-branding/src"/>
          <fileset dir="./adt/idea/adt-testutils/src/main/java"/>
          <fileset dir="./adt/idea/adt-ui-model/src/main/java"/>
          <fileset dir="./adt/idea/adt-ui/src/main/java"/>
          <fileset dir="./adt/idea/android-adb/src"/>
          <fileset dir="./adt/idea/android-common/src"/>
          <fileset dir="./adt/idea/android-debuggers/src"/>
          <fileset dir="./adt/idea/android/gen"/>
          <fileset dir="./adt/idea/android-lang/gen"/>
          <fileset dir="./adt/idea/android-lang/src"/>
          <fileset dir="./adt/idea/android-layout-inspector/src"/>
          <fileset dir="./adt/idea/android/src"/>
          <fileset dir="./adt/idea/android/src/org/jetbrains/android/uipreview"/>
          <fileset dir="./adt/idea/apkanalyzer/src"/>
          <fileset dir="./adt/idea/assistant/src"/>
          <fileset dir="./adt/idea/build-common/src"/>
          <fileset dir="./adt/idea/connection-assistant/src"/>
          <fileset dir="./adt/idea/designer/src"/>
          <fileset dir="./adt/idea/jps-plugin/src"/>
          <fileset dir="./adt/idea/layoutlib/src"/>
          <fileset dir="./adt/idea/native-symbolizer/src"/>
          <fileset dir="./adt/idea/observable-demo/src"/>
          <fileset dir="./adt/idea/observable/src"/>
          <fileset dir="./adt/idea/observable-ui/src"/>
          <fileset dir="./adt/idea/perfd-host/src/main/java"/>
          <fileset dir="./adt/idea/profilers-android/src"/>
          <fileset dir="./adt/idea/profilers/src"/>
          <fileset dir="./adt/idea/profilers-ui/src"/>
          <fileset dir="./adt/idea/project-system-gradle/src"/>
          <fileset dir="./adt/idea/project-system/src"/>
          <fileset dir="./adt/idea/sdk-updates/src"/>
          <fileset dir="./adt/idea/smali/gen"/>
          <fileset dir="./adt/idea/smali/src"/>
          <fileset dir="./adt/idea/uitest-framework/src"/>
          <fileset dir="./adt/idea/updater-ui/src"/>
          <fileset dir="./adt/idea/whats-new-assistant/src"/>
          <fileset dir="./adt/idea/wizard-model/src"/>
          <fileset dir="./adt/idea/wizard/src"/>
          <fileset dir="./analytics-library/inspector/src/main/java"/>
          <fileset dir="./analytics-library/publisher/src/main/java"/>
          <fileset dir="./analytics-library/shared/src/main/java"/>
          <fileset dir="./analytics-library/testing/src/main/java"/>
          <fileset dir="./analytics-library/tracker/src/main/java"/>
          <fileset dir="./apksig/src/apksigner/java"/>
          <fileset dir="./apksig/src/main/java"/>
          <fileset dir="./apkzlib/src/main/java"/>
          <fileset dir="./base/annotations/src/main/java"/>
          <fileset dir="./base/apkparser/analyzer/src/main/java"/>
          <fileset dir="./base/apkparser/binary-resources/src/main/java"/>
          <fileset dir="./base/apkparser/cli/src/main/java"/>
          <fileset dir="./base/apps/NotificationStudio/src"/>
          <fileset dir="./base/apps/SdkController/src"/>
          <fileset dir="./base/bazel/sdk/src"/>
          <fileset dir="./base/bazel/src"/>
          <fileset dir="./base/build-system/builder-model/src/main/java"/>
          <fileset dir="./base/build-system/builder/src/main/java"/>
          <fileset dir="./base/build-system/builder-test-api/src/main/java"/>
          <fileset dir="./base/build-system/debug/model/src/main/java"/>
          <fileset dir="./base/build-system/gradle-api/src/main/java"/>
          <fileset dir="./base/build-system/gradle-core/src/fromGradle/java"/>
          <fileset dir="./base/build-system/gradle-core/src/main/java"/>
          <fileset dir="./base/build-system/gradle-experimental/src/main/java"/>
          <fileset dir="./base/build-system/integration-test/framework/src/main/java"/>
          <fileset dir="./base/build-system/java-lib-plugin/java-lib-model-builder/src/main/java"/>
          <fileset dir="./base/build-system/java-lib-plugin/java-lib-model/src/main/java"/>
          <fileset dir="./base/build-system/manifest-merger/src/main/java"/>
          <fileset dir="./base/build-system/profile/src/main/java"/>
          <fileset dir="./base/build-system/project-test-lib/src/main/java"/>
          <fileset dir="./base/build-system/project-test/src/main/java"/>
          <fileset dir="./base/chunkio-processor/src"/>
          <fileset dir="./base/chunkio/src/main/java"/>
          <fileset dir="./base/common/src/main/java"/>
          <fileset dir="./base/ddmlib/src/main/java"/>
          <fileset dir="./base/devicelib/src/main/java"/>
          <fileset dir="./base/device_validator/app/src"/>
          <fileset dir="./base/device_validator/dvlib/src/main/java"/>
          <fileset dir="./base/draw9patch/src/main/java"/>
          <fileset dir="./base/fakeadbserver/src/main/java"/>
          <fileset dir="./base/flags/src/main/java"/>
          <fileset dir="./base/jaxb-inheritance-plugin/src/main/java"/>
          <fileset dir="./base/jobb/src/main/java"/>
          <fileset dir="./base/jobb/src/main/java/Twofish"/>
          <fileset dir="./base/layoutinspector/src"/>
          <fileset dir="./base/layoutlib-api/src/main/java"/>
          <fileset dir="./base/legacy/archquery/src/main/java"/>
          <fileset dir="./base/lint/cli/src/main/java"/>
          <fileset dir="./base/lint/libs/intellij-core/src/main/java"/>
          <fileset dir="./base/lint/libs/kotlin-compiler/src/main/java"/>
          <fileset dir="./base/lint/libs/lint-api/src/main/java"/>
          <fileset dir="./base/lint/libs/lint-checks/src/main/java"/>
          <fileset dir="./base/lint/libs/lint-gradle/src/main/java"/>
          <fileset dir="./base/lint/libs/lint-tests/src/main/java"/>
          <fileset dir="./base/lint/libs/uast/src/main/java"/>
          <fileset dir="./base/misc/api-generator/src/main/java"/>
          <fileset dir="./base/misc/screenshot2/src/main/java"/>
          <fileset dir="./base/ninepatch/src/main/java"/>
          <fileset dir="./base/perflib/src/main/java"/>
          <fileset dir="./base/perf-logger/src/main/java"/>
          <fileset dir="./base/pixelprobe/src/main/generated"/>
          <fileset dir="./base/pixelprobe/src/main/java"/>
          <fileset dir="./base/profiler/app/common/src/main/java"/>
          <fileset dir="./base/profiler/app/perfa-okhttp/src/main/java"/>
          <fileset dir="./base/profiler/app/perfa/src/main/java"/>
          <fileset dir="./base/profiler/app/supportlib/src/main/java"/>
          <fileset dir="./base/profiler/integration-tests/ProfilerApp/app/src/androidTest/java"/>
          <fileset dir="./base/profiler/integration-tests/ProfilerApp/app/src/main/java"/>
          <fileset dir="./base/profiler/transform/src/main/java"/>
          <fileset dir="./base/repository/src/main/java"/>
          <fileset dir="./base/sdk-common/aia-manifest-jar-generator/src"/>
          <fileset dir="./base/sdk-common/generate-locale-data/src/main/java"/>
          <fileset dir="./base/sdk-common/src/main/java"/>
          <fileset dir="./base/sdklib/src/main/java"/>
          <fileset dir="./base/testing-infrastructure/device-pool/device-provider/src/main/java"/>
          <fileset dir="./base/testutils/src/main/java"/>
          <fileset dir="./base/usb-devices/src"/>
          <fileset dir="./base/vector-drawable-tool/src/main/java"/>
          <fileset dir="./buildSrc/src/fromGradle/groovy/org/gradle/build"/>
          <fileset dir="./buildSrc/src/fromGradle/groovy/org/gradle/build/docs"/>
          <fileset dir="./buildSrc/src/fromGradle/groovy/org/gradle/build/docs/dsl/docbook"/>
          <fileset dir="./buildSrc/src/fromGradle/groovy/org/gradle/build/docs/dsl/docbook/model"/>
          <fileset dir="./buildSrc/src/fromGradle/groovy/org/gradle/build/docs/dsl/links"/>
          <fileset dir="./buildSrc/src/fromGradle/groovy/org/gradle/build/docs/dsl/source"/>
          <fileset dir="./buildSrc/src/fromGradle/groovy/org/gradle/build/docs/dsl/source/model"/>
          <fileset dir="./buildSrc/src/fromGradle/groovy/org/gradle/build/docs/model"/>
          <fileset dir="./buildSrc/src/fromGradle/groovy/org/gradle/plugins/jsoup"/>
          <fileset dir="./buildSrc/src/fromGradle/groovy/org/gradle/plugins/pegdown"/>
          <fileset dir="./buildSrc/src/main/groovy"/>
          <fileset dir="./buildSrc/src/main/java"/>
          <fileset dir="./data-binding/baseLibrary/src/main/java/androidx/databinding"/>
          <fileset dir="./data-binding/compilerCommon/src/main/grammar-gen/android/databinding/parser"/>
          <fileset dir="./data-binding/compilerCommon/src/main/java/android/databinding/tool"/>
          <fileset dir="./data-binding/compilerCommon/src/main/java/android/databinding/tool/expr"/>
          <fileset dir="./data-binding/compilerCommon/src/main/java/android/databinding/tool/processing"/>
          <fileset dir="./data-binding/compilerCommon/src/main/java/android/databinding/tool/processing/scopes"/>
          <fileset dir="./data-binding/compilerCommon/src/main/java/android/databinding/tool/store"/>
          <fileset dir="./data-binding/compilerCommon/src/main/java/android/databinding/tool/util"/>
          <fileset dir="./data-binding/compilerCommon/src/main/java/android/databinding/tool/writer"/>
          <fileset dir="./data-binding/compilerCommon/src/main/kotlin/android/databinding/tool/ext"/>
          <fileset dir="./data-binding/compilerCommon/src/main/kotlin/android/databinding/tool/writer"/>
          <fileset dir="./data-binding/compilerCommon/src/main/xml-gen/android/databinding/parser"/>
          <fileset dir="./data-binding/compiler/src/main/java/android/databinding/annotationprocessor"/>
          <fileset dir="./data-binding/compiler/src/main/java/android/databinding/tool"/>
          <fileset dir="./data-binding/compiler/src/main/java/android/databinding/tool/expr"/>
          <fileset dir="./data-binding/compiler/src/main/java/android/databinding/tool/reflection"/>
          <fileset dir="./data-binding/compiler/src/main/java/android/databinding/tool/reflection/annotation"/>
          <fileset dir="./data-binding/compiler/src/main/java/android/databinding/tool/solver"/>
          <fileset dir="./data-binding/compiler/src/main/java/android/databinding/tool/store"/>
          <fileset dir="./data-binding/compiler/src/main/java/android/databinding/tool/util"/>
          <fileset dir="./data-binding/compiler/src/main/java/android/databinding/tool/writer"/>
          <fileset dir="./data-binding/compiler/src/main/kotlin/android/databinding/tool/expr"/>
          <fileset dir="./data-binding/compiler/src/main/kotlin/android/databinding/tool/writer"/>
          <fileset dir="./data-binding/developmentPlugins/localizeMavenPlugin/src/main/groovy/android/databinding"/>
          <fileset dir="./data-binding/exec/src/main/java/android/databinding"/>
          <fileset dir="./data-binding/exec/src/main/java/android/databinding/cli"/>
          <fileset dir="./data-binding/extensions/library/src/doc/java"/>
          <fileset dir="./data-binding/gradlePlugin/src/main/java/android/databinding/tool"/>
          <fileset dir="./data-binding/samples/BindingDemo/app/src/main/java"/>
          <fileset dir="./dx/dalvik/dexgen/src"/>
          <fileset dir="./dx/dalvik/dx/src"/>
          <fileset dir="./dx/dalvik/tools/dexdeps/src"/>
          <fileset dir="./external/desugar/java"/>
          <fileset dir="./external/fat32lib/src/main/java/de/waldheinz/fs"/>
          <fileset dir="./external/fat32lib/src/main/java/de/waldheinz/fs/fat"/>
          <fileset dir="./external/fat32lib/src/main/java/de/waldheinz/fs/util"/>
          <fileset dir="./idea/jps/antUiTest/src"/>
          <fileset dir="./idea/studio/src/main/java"/>
          <fileset dir="./vendor/google/android-apk/src"/>
          <fileset dir="./vendor/google/android-ndk/src"/>
          <fileset dir="./vendor/google/dogfood/plugin/src"/>
          <fileset dir="./vendor/google/GooglePlayLog"/>
        </sourcefiles>
      </structure>
      <html destdir="../out/report"/>
    </jacoco:report>
  </target>
</project>
