exports_files(["dependencies.properties"])

filegroup(
    name = "agp_gradle_build_files",
    srcs = glob([
        "*.gradle",
        "*.properties",
    ]),
    visibility = [
        "//tools/base/build-system:__pkg__",
        "//tools/base/firebase/testlab/testlab-gradle-plugin:__pkg__",
        "//tools/base/preview/screenshot/screenshot-test-gradle-plugin:__pkg__",
        "//tools/base/utp:__pkg__",
    ],
)
