exports_files(["version.properties"])

exports_files(["dependencies.properties"])

filegroup(
    name = "agp_gradle_build_files",
    srcs = glob([
        "*.gradle",
        "*.properties",
    ]),
    visibility = [
        "//tools/base/build-system:__pkg__",
        "//tools/base/utp:__pkg__",
    ],
)
