org.gradle.parallel=true
org.gradle.jvmargs=-Xmx4096m
org.gradle.daemon=true
# Flags set in Gradle at head that we can also benefit from
# See https://github.com/gradle/gradle/blob/master/gradle.properties
org.gradle.vfs.watch=true
systemProp.org.gradle.unsafe.vfs.partial-invalidation=true
org.gradle.caching=true
kotlin.caching.enabled=true
# Don't use "fail" until this is fixed: https://youtrack.jetbrains.com/issue/IDEA-272594
org.gradle.warning.mode=all
# Disable configuration cache due to b/282203447
org.gradle.unsafe.configuration-cache=false