include ':base:annotations'
include ':base:api-generator'
include ':apkzlib'
include ':base:archquery'
include ':base:asset-studio'
include ':base:common'
include ':base:docs'
include ':base:devicelib'
include ':base:ddmlib'
include ':base:draw9patch'
include ':base:fakeadbserver'
include ':base:dvlib'
include ':base:jobb'
include ':base:layoutlib-api'
include ':base:layoutlib-extensions'
include ':base:lint'
include ':base:lint-api'
include ':base:lint-checks'
include ':base:lint-gradle-api'
include ':base:lint-gradle'
include ':base:lint-kotlin'
include ':base:lint-model'
include ':base:lint-tests'
include ':base:uast'
include ':base:intellij-core'
include ':base:kotlin-compiler'
include ':base:manifest-merger'
include ':base:mlkit-common'
include ':base:ninepatch'
include ':base:screenshot2'
include ':base:repository'
include ':base:jaxb-inheritance-plugin'
include ':base:sdk-common'
include ':base:sdklib'
include ':base:testutils'
include ':base:gradle-import'
include ':base:vector-drawable-tool'
include ':base:chunkio'
include ':base:pixelprobe'

include ':base:profile'
include ':base:builder-model'
include ':base:builder-test-api'
include ':base:builder'
include ':base:gradle-api'
include ':base:build-system:gradle-core'
include ':base:build-system:aapt2'
include ':base:build-system:aapt2-proto'
include ':base:build-system:aaptcompiler'
include ':base:build-system:integration-test'
include ':base:build-system:integration-test:framework'
include ':base:build-system:integration-test:api'
include ':base:build-system:integration-test:application'
include ':base:build-system:integration-test:connected'
include ':base:build-system:integration-test:databinding'
include ':base:build-system:integration-test:databinding:incremental'
include ':base:build-system:integration-test:lint'
include ':base:build-system:integration-test:native'
include ':base:project-test-lib'
include ':base:project-test'
include ':base:build-system:debug:model'

include ':base:templates'

include ':base:testing-infrastructure:device-pool:device-provider'

project(':base:api-generator'      ).projectDir = new File(rootDir, 'base/misc/api-generator')
project(':base:archquery'          ).projectDir = new File(rootDir, 'base/legacy/archquery')
project(':base:dvlib'              ).projectDir = new File(rootDir, 'base/device_validator/dvlib')
project(':base:lint'               ).projectDir = new File(rootDir, 'base/lint/cli')
project(':base:lint-api'           ).projectDir = new File(rootDir, 'base/lint/libs/lint-api')
project(':base:lint-checks'        ).projectDir = new File(rootDir, 'base/lint/libs/lint-checks')
project(':base:lint-gradle-api'    ).projectDir = new File(rootDir, 'base/lint/libs/lint-gradle-api')
project(':base:lint-gradle'        ).projectDir = new File(rootDir, 'base/lint/libs/lint-gradle')
project(':base:lint-kotlin'        ).projectDir = new File(rootDir, 'base/lint/libs/lint-kotlin')
project(':base:lint-model'         ).projectDir = new File(rootDir, 'base/lint/libs/lint-model')
project(':base:lint-tests'         ).projectDir = new File(rootDir, 'base/lint/libs/lint-tests')
project(':base:uast'               ).projectDir = new File(rootDir, 'base/lint/libs/uast')
project(':base:intellij-core'      ).projectDir = new File(rootDir, 'base/lint/libs/intellij-core')
project(':base:kotlin-compiler'    ).projectDir = new File(rootDir, 'base/lint/libs/kotlin-compiler')
project(':base:screenshot2'        ).projectDir = new File(rootDir, 'base/misc/screenshot2')

project(':base:profile'            ).projectDir = new File(rootDir, 'base/build-system/profile')
project(':base:builder-model'      ).projectDir = new File(rootDir, 'base/build-system/builder-model')
project(':base:builder-test-api'   ).projectDir = new File(rootDir, 'base/build-system/builder-test-api')
project(':base:builder'            ).projectDir = new File(rootDir, 'base/build-system/builder')
project(':base:docs'               ).projectDir = new File(rootDir, 'base/build-system/docs')
project(':base:manifest-merger'    ).projectDir = new File(rootDir, 'base/build-system/manifest-merger')
project(':base:gradle-api'      ).projectDir = new File(rootDir, 'base/build-system/gradle-api')
project(':base:project-test-lib'   ).projectDir = new File(rootDir, 'base/build-system/project-test-lib')
project(':base:project-test'       ).projectDir = new File(rootDir, 'base/build-system/project-test')

include ':external:fat32lib'
include ':external:desugar'
include ':external:desugar:tryWithResourcesRuntime'
project(':external:desugar:tryWithResourcesRuntime').projectDir =
        new File(project(':external:desugar').projectDir, "java/com/google/devtools/build/android/desugar/runtime")

include ':dataBinding'
project(':dataBinding').projectDir = new File(rootDir, "data-binding")
include ':dataBinding:baseLibrary'
project(':dataBinding:baseLibrary').projectDir = new File(rootDir, "data-binding/baseLibrary")
include ':dataBinding:baseLibrarySupport'
project(':dataBinding:baseLibrarySupport').projectDir = new File(rootDir, "data-binding/baseLibrarySupport")
include ':dataBinding:compiler'
project(':dataBinding:compiler').projectDir = new File(rootDir, "data-binding/compiler")
include ':dataBinding:compilerCommon'
project(':dataBinding:compilerCommon').projectDir = new File(rootDir, "data-binding/compilerCommon")

include ':analytics-library:inspector'
include ':analytics-library:protos'
include ':analytics-library:shared'
include ':analytics-library:tracker'
include ':analytics-library:publisher'
include ':analytics-library:testing'
include ':analytics-library:crash'

include ':base:apkparser:binary-resources'
project(':base:apkparser:binary-resources'    ).projectDir = new File(rootDir, 'base/apkparser/binary-resources')
include ':base:apkparser:apkanalyzer'
project(':base:apkparser:apkanalyzer'        ).projectDir = new File(rootDir, 'base/apkparser/analyzer')
include ':base:apkparser:apkanalyzer-cli'
project(':base:apkparser:apkanalyzer-cli'    ).projectDir = new File(rootDir, 'base/apkparser/cli')

include ':apksig'
project(':apksig').buildFileName = 'android_plugin_for_gradle.gradle'

include ':dx'
project(':dx').projectDir = new File(rootDir, 'dx/dalvik/dx')

include ':base:java-lib-model'
project(':base:java-lib-model'        ).projectDir = new File(rootDir, 'base/build-system/java-lib-plugin/java-lib-model')
include ':base:java-lib-model-builder'
project(':base:java-lib-model-builder').projectDir = new File(rootDir, 'base/build-system/java-lib-plugin/java-lib-model-builder')

include ':base:zipflinger'
include ':base:signflinger'
