rootProject.name = 'tools-gradle'
include ':base:api-generator'
include ':base:archquery'
include ':base:asset-studio'
include ':base:bazel:avd'
include ':base:bazel:repolinker'
include ':base:devicelib'
include ':base:jobb'
include ':base:layoutlib-extensions'
include ':base:lint'
include ':base:manifest-merger'
include ':base:mlkit-common'
include ':base:screenshot2'
include ':base:gradle-import'
include ':base:vector-drawable-tool'
include ':base:profgen'
include ':base:profgen-cli'

include ':base:profile'
include ':base:builder-model'
include ':base:builder-test-api'
include ':base:builder'
include ':base:gradle-api'
include ':base:build-analyzer:common'
include ':base:build-system:gradle-core'
include ':base:build-system:gradle-kotlin'
include ':base:build-system:gradle-settings'
include ':base:build-system:gradle-settings-api'
include ':base:build-system:aapt2'
include ':base:build-system:aapt2-proto'
include ':base:build-system:aaptcompiler'
include ':base:build-system:docs'
include ':base:build-system:integration-test'
include ':base:build-system:integration-test:framework'
include ':base:build-system:integration-test:api'
include ':base:build-system:integration-test:application'
include ':base:build-system:integration-test:connected'
include ':base:build-system:integration-test:databinding'
include ':base:build-system:integration-test:databinding:incremental'
include ':base:build-system:integration-test:lint'
include ':base:build-system:integration-test:managed-devices'
include ':base:build-system:integration-test:native'
include ':base:build-system:integration-test:utp'
include ':base:build-system:builder-r8'
include ':base:build-system:shrinker'
include ':base:project-test-lib'
include ':base:project-test'
include ':base:build-system:debug:model'
include ':base:kotlin-multiplatform-models'

include ':base:testing-infrastructure:device-pool:device-provider'

project(':base:api-generator'      ).projectDir = new File(rootDir, 'base/misc/api-generator')
project(':base:archquery'          ).projectDir = new File(rootDir, 'base/legacy/archquery')
project(':base:screenshot2'        ).projectDir = new File(rootDir, 'base/misc/screenshot2')

project(':base:profile'            ).projectDir = new File(rootDir, 'base/build-system/profile')
project(':base:builder-model'      ).projectDir = new File(rootDir, 'base/build-system/builder-model')
project(':base:builder-test-api'   ).projectDir = new File(rootDir, 'base/build-system/builder-test-api')
project(':base:builder'            ).projectDir = new File(rootDir, 'base/build-system/builder')
project(':base:manifest-merger'    ).projectDir = new File(rootDir, 'base/build-system/manifest-merger')
project(':base:gradle-api'         ).projectDir = new File(rootDir, 'base/build-system/gradle-api')
project(':base:project-test-lib'   ).projectDir = new File(rootDir, 'base/build-system/project-test-lib')
project(':base:project-test'       ).projectDir = new File(rootDir, 'base/build-system/project-test')
project(':base:profgen'            ).projectDir = new File(rootDir, 'base/profgen/profgen')
project(':base:profgen-cli'        ).projectDir = new File(rootDir, 'base/profgen/profgen-cli')

include ':external:fat32lib'
include ':data-binding'

include ':base:utp:android-device-provider-ddmlib'
include ':base:utp:android-device-provider-gradle'
include ':base:utp:android-device-provider-profile'
include ':base:utp:android-test-plugin-host-additional-test-output'
include ':base:utp:android-test-plugin-host-apk-installer'
include ':base:utp:android-test-plugin-host-coverage'
include ':base:utp:android-test-plugin-host-device-info'
include ':base:utp:android-test-plugin-host-logcat'
include ':base:utp:android-test-plugin-host-emulator-control'
include ':base:utp:android-test-plugin-host-retention'
include ':base:utp:android-test-plugin-result-listener-gradle'
include ':base:utp:utp-common'
include ':base:perf-logger'

include ':base:firebase:testlab:testlab-gradle-plugin'
include ':base:preview:screenshot:screenshot-test-gradle-plugin'
include ':base:preview:screenshot:screenshot-validation-junit-engine'

